In [8]:
import pandas as pd
file = 'filesud.csv'
df = pd.read_csv(file)
#print(df.describe())
#print(df.head())

import numpy as np
size = 10
x = np.zeros((size,9,9),dtype='uint8')
y = np.zeros((size,9,9),dtype='uint8')

df = df.values

def process_matrix(series):
    series = str(series)
    np_small = np.array([int (x) for x in list(series)])
    return np_small.reshape((9,9))

for i in range(size):
    quiz = df[i,0]
    soln = df[i,1]
    x[i] = process_matrix(quiz)
    y[i] = process_matrix(soln)

board = x[0]
print(board)

[[0 0 4 3 0 0 2 0 9]
 [0 0 5 0 0 9 0 0 1]
 [0 7 0 0 6 0 0 4 3]
 [0 0 6 0 0 2 0 8 7]
 [1 9 0 0 0 7 4 0 0]
 [0 5 0 0 8 3 0 0 0]
 [6 0 0 0 0 0 1 0 5]
 [0 0 3 5 0 8 6 9 0]
 [0 4 2 9 1 0 3 0 0]]


In [9]:
def norm(a):
    return (a / 9) - .5

def denorm(a):
    return (a + .5) * 9

In [10]:
def is_possible(_board, row, col, val):
    for _j in range(0, 9):
        if _board[row][_j] == val:
            return False

    for _i in range(0, 9):
        if _board[_i][col] == val:
            return False

    startRow = (row // 3) * 3
    startCol = (col // 3) * 3
    for i in range(0, 3):
        for _j in range(0, 3):
            if _board[startRow + i][startCol + _j] == val:
                return False

    return True
    

In [11]:
def solve():
    _sol = board
    for _i in range(0, 9):
        for _j in range(0, 9):
            if board[_i][_j] == 0:
                for val in range(1, 10):
                    if is_possible(board, _i, _j, val):
                        board[_i][_j] = val
                        solve()

                        # Bad choice, make it blank and go back
                        board[_i][_j] = 0
                return
    print(board)

In [13]:
for i in range(10):
  board = x[i]
  print("Result of backtrack for test puzzle:", i)
  solve()
  print('- - - - - - - - - - - -')
  print("Correct Solution for puzzle:", i)
  print(y[i])
  print('----------------------------------')

Result of backtrack for test puzzle: 0
[[8 6 4 3 7 1 2 5 9]
 [3 2 5 8 4 9 7 6 1]
 [9 7 1 2 6 5 8 4 3]
 [4 3 6 1 9 2 5 8 7]
 [1 9 8 6 5 7 4 3 2]
 [2 5 7 4 8 3 9 1 6]
 [6 8 9 7 3 4 1 2 5]
 [7 1 3 5 2 8 6 9 4]
 [5 4 2 9 1 6 3 7 8]]
- - - - - - - - - - - -
Correct Solution for puzzle: 0
[[8 6 4 3 7 1 2 5 9]
 [3 2 5 8 4 9 7 6 1]
 [9 7 1 2 6 5 8 4 3]
 [4 3 6 1 9 2 5 8 7]
 [1 9 8 6 5 7 4 3 2]
 [2 5 7 4 8 3 9 1 6]
 [6 8 9 7 3 4 1 2 5]
 [7 1 3 5 2 8 6 9 4]
 [5 4 2 9 1 6 3 7 8]]
----------------------------------
Result of backtrack for test puzzle: 1
[[3 4 6 1 7 9 2 5 8]
 [1 8 7 5 2 3 9 6 4]
 [5 2 9 6 4 8 3 7 1]
 [9 6 5 8 3 2 4 1 7]
 [4 7 2 9 1 6 8 3 5]
 [8 1 3 7 5 4 6 2 9]
 [7 9 8 2 6 1 5 4 3]
 [6 3 1 4 8 5 7 9 2]
 [2 5 4 3 9 7 1 8 6]]
- - - - - - - - - - - -
Correct Solution for puzzle: 1
[[3 4 6 1 7 9 2 5 8]
 [1 8 7 5 2 3 9 6 4]
 [5 2 9 6 4 8 3 7 1]
 [9 6 5 8 3 2 4 1 7]
 [4 7 2 9 1 6 8 3 5]
 [8 1 3 7 5 4 6 2 9]
 [7 9 8 2 6 1 5 4 3]
 [6 3 1 4 8 5 7 9 2]
 [2 5 4 3 9 7 1 8 6]]
-----------------